### ISSUE TITLE
Use Nitro json files with puppet-swagger-generator ?

### ISSUE THREAD

**Issue by kernel23** [chiradeep/go-nitro#1]
Hi @chiradeep,
Do you think we could use all your JSON files with [puppet-swagger-generator](https://github.com/garethr/puppet-swagger-generator) from @garethr ?
Thanks !

**Comment by chiradeep** [comment]
The json schema isn't a swagger specification so I don't think that will work

**Comment by garethr** [comment]
@kernel23 @chiradeep it would probably be possible to take a similar approach, ie. to use the json documents to generate the relevant puppet types and providers. My colleague @mrzarquon might be interested in this too

**Comment by kernel23** [comment]
Thanks for your answers. Please keep me in touch if anybody feels to help on this topic. It could be very nice to control Citrix Netscaler from puppet resources.

**Comment by chiradeep** [comment]
Have you seen https://github.com/puppetlabs/puppetlabs-netscaler? 
Or for Ansible
https://github.com/citrix/netscaler-ansible-modules
