### ISSUE TITLE
Unable to update Route resource - 400 Bad Request

### ISSUE THREAD

**Issue by sagarnikam123** [chiradeep/go-nitro#16]
Using [NetScaler CPX Express ](https://store.docker.com/images/netscaler-cpx-express-rel-120-experimental) for local testing.

Component :- Network.Route

While updating route resource, got a _400 Bad Request_ error

- **route.go**
```
package main

import (
	"fmt"

	"github.com/chiradeep/go-nitro/config/network"
	"github.com/chiradeep/go-nitro/netscaler"
)

func main() {
	client, _ := netscaler.NewNitroClientFromEnv()
	route := network.Route{
		Network: "192.168.15.0",
		Netmask: "255.255.255.0",
		Gateway: "172.17.0.2",
	}

	// adding route
	result, err := client.AddResource(netscaler.Route.Type(), "awsRoute", &route)
	if err == nil {
		client.SaveConfig()
	}
	fmt.Println(result)

	// updating route
	routeUpdated := network.Route{
		Network: "192.168.15.0",
		Netmask: "255.255.255.0",
		Gateway: "172.17.0.2",
		Msr:     "ENABLED",
		Monitor: "PING",
	}
	updateResult, updateError := client.ChangeResource(netscaler.Route.Type(), "192.168.15.0", routeUpdated)

	if updateError == nil {
		fmt.Println(updateResult)
	}
	fmt.Println(updateError)
}
```
- **console error** - 
```
2018/05/15 14:56:39 [DEBUG] go-nitro: listing resource of type  route , name:  192.168.15.0
2018/05/15 14:56:39 [TRACE] go-nitro: url is  http://172.17.0.2/nitro/v1/config/route/192.168.15.0
2018/05/15 14:56:39 [DEBUG] go-nitro: response Status: 400 Bad Request
2018/05/15 14:56:39 [INFO] go-nitro: read: error = { "errorcode": 1095, "message": "Required argument missing [netmask, network]", "severity": "ERROR" }
2018/05/15 14:56:39 [INFO] go-nitro: No route 192.168.15.0 found
192.168.15.0
<nil>
```
Instead of `ChangeResource(resourceType string, name string, resourceStruct interface{})`
 or
 `updateResource(resourceType string, resourceName string, resourceJSON []byte)`
Can we have `ChangeResourceWithArgsMap(resourceType string, resourceName string, argsMap map[string]string)` in client ?

Also please have a quick thought on modifying `FindResource` function to something like `FindResourceWithArgsMap(resourceType string, resourceName string, argsMap map[string]string)`
Because if we want to read the resource which don't have unique id/name, in this case, we are dependant on parameters & its values for finding the resource.

**Comment by chiradeep** [comment]
You need to use UpdateResource and leave the resourceName as `""` . If that doesn't work, perhaps it is a small change in updateResource in netscaler_resource.go
Pull requests are accepted

**Comment by sagarnikam123** [comment]
Using `UpdateResource` solves the problem. Thanks !!!
