### ISSUE TITLE
missing properties in responderaction

### ISSUE THREAD

**Issue by sl-eddycharly** [chiradeep/go-nitro#20]
"reasonphrase" and "responsestatuscode" seem to be missing in resource responderaction.

**Comment by chiradeep** [comment]
Code was generated using the 10.5 API. Looks like this is new in 11/12. PR will be accepted to update this struct

**Comment by sl-eddycharly** [comment]
Ok, thanks.

**Comment by doubret** [comment]
Hi,
If you're interested, i started another project in the same spirit.

What i did was to create yaml specs for various resources and bindings form the official documentation (https://github.com/doubret/citrix-netscaler-nitro-12-yaml-specs and https://github.com/doubret/citrix-netscaler-nitro-11-yaml-specs).

From these yaml spec files, i generate a nitro go client (https://github.com/doubret/citrix-netscaler-nitro-go-client).

And finally, i generate a terraform provider (https://github.com/doubret/terraform-provider-netscaler).
I took a different approach as yours regarding the terraform provider as i consider bindings as resources from the terraform point of view.

There's still a lot of work to do but it begins to work correctly.
Currently i'm adding unit tests to the nitro client.
Once it's done i'll continue adding new resources.

Thanks for the inspiration.
Regards.

**Comment by chiradeep** [comment]
closed by 82bb933547b7
