### ISSUE TITLE
How do i use go-nitro unbind Server from ServiceGroup

### ISSUE THREAD

**Issue by sak0** [chiradeep/go-nitro#21]
I can bind the server to servicegroup by this way:
`	client, _ := netscaler.NewNitroClientFromEnv()

	binding := basic.Servicegroupservicegroupmemberbinding{}

	_, err := client.AddResource(netscaler.Servicegroup_servicegroupmember_binding.Type(), groupName, &binding)`
But i can't find the right way for unbind server from servicegroup, could you please help me?

**Comment by sl-eddycharly** [comment]
What i did was using DeleteResourceWithArgsMap passing the servicegroupname, servername and port.

**Comment by sak0** [comment]
@sl-eddycharly 
It works, thanks

**Comment by chiradeep** [comment]
Thanks @sl-eddycharly
