### ISSUE TITLE
Printing the headers prints out the password

### ISSUE THREAD

**Issue by jovandeginste** [chiradeep/go-nitro#46]
Since [this change](https://github.com/chiradeep/go-nitro/commit/c8d3cbc084794b4b1728dc9fd8d309f074f2b0b0#diff-b63013a5cc74939bf21aa3c8274194a2d38e2ed0c5604f70e7d20a6fa8aa7312R159), the password used to connect (eg. through the env var) is now printed in the logs.

**Comment by jantytgat** [comment]
Chiming in, is there a reason why the library is printing to the console/log?
Can this be disabled? I don't want any output from a library messing up my console application.

**Comment by jovandeginste** [comment]
Ideally, this is configuration (set a logger when creating a client)

**Comment by jantytgat** [comment]
Shouldn't it be deactivated at all times, thus no logging except through error handling to indicate something is wrong?

I removed all log interfaces and still it prints through fmt.Println(), which doesn't seem like a good idea?

**Comment by jovandeginste** [comment]
I don't mind customizable logging through a known library such as logsrus. This allows disabling by default, or enabling per level (error, warn, etc). I don't want my password to be printed out by default, such as is now the case. The verbosity as it is now, is annoying in any project where I use this library, but turning prints off completely makes errors invisible...
