### ISSUE TITLE
Getting 404 while creating servicegroup

### ISSUE THREAD

**Issue by sanket4373** [chiradeep/go-nitro#9]
I want to bind a server to a servicegroup. I can create a server however, when I try creating a servicegroup I am getting a `go-nitro: response Status: 404 Not Found` .  Ironically, I can see a servicegroup getting created on my Netscaler. Below is my code snippet:

```
createServer :=  basic.Server{
            Ipaddress: "<private_ip_of_server>",
            Name: "test-server",
        }

        client.AddResource(netscaler.Server.Type(), "create_server", &createServer)

        createSvcGrp := basic.Servicegroup{
            Servicegroupname: "test-svc-grp",
            Servicetype: "TCP",
            Weight: 1,
            Port: 22,
            Servername: "test-server",
        }

        client.AddResource(netscaler.Servicegroup.Type(), "create_servicegroup", &createSvcGrp)
```

I would like to understand why isn't the `server-servicegroup` binding working ?

**Comment by chiradeep** [comment]
The Servername parameter is only valid for Unset and Update operations, not ADD.
https://developer-docs.citrix.com/projects/netscaler-nitro-api/en/12.0/configuration/basic/servicegroup/servicegroup/#add 

The way to make a binding is to:
- create the parent object (servicegroup)
- create the child object (server)
- bind the parent and child object using the servicegroup_servicegroupmember_binding.
This allows you to bind multiple servers to the service group.
See the examples directory for examples
